### ISSUE TITLE
Erratic ELEMENT_CONVERSION_FAILURE deserializing commitment

### ISSUE THREAD

**Issue by ruescasd** [agoravoting/sandbox#1]
When verifying a mix, the following line:

val commitment2 = spg.getCommitmentSpace().getElementFromString(shuffleProof.mixProof.commitment)

sometimes throws an exception (see below example trace). The problem occurs when converting the commitment from a string, at this line:

ch.bfh.unicrypt.math.algebra.general.abstracts.AbstractSet.getElementFrom(AbstractSet.java:324)

and traced back to this line

ch.bfh.unicrypt.math.algebra.general.classes.ProductSet.defaultGetElementFrom(ProductSet.java:291)

Have not managed to reproduce this bug reliably. It seems to occur more frequently for runs with a high number of votes. 

Full stack trace
=============================================================================

UniCryptException[ELEMENT_CONVERSION_FAILURE]
       at ch.bfh.unicrypt.math.algebra.general.abstracts.AbstractSet.getElementFrom(AbstractSet.java:324)
        at ch.bfh.unicrypt.math.algebra.general.abstracts.AbstractSet.getElementFrom(AbstractSet.java:387)
        at ch.bfh.unicrypt.math.algebra.general.abstracts.AbstractSet.getElementFromString(AbstractSet.java:395)
        at Verifier$.verifyShuffle(Verifier.scala:151)
        at Election$.addMix(Election.scala:183)
        at ElectionTest$$anonfun$8.apply(Demo.scala:162)
        at ElectionTest$$anonfun$8.apply(Demo.scala:160)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: UniCryptException[ELEMENT_CONVERSION_FAILURE]
        at ch.bfh.unicrypt.math.algebra.general.classes.ProductSet.defaultGetElementFrom(ProductSet.java:291)
        at ch.bfh.unicrypt.math.algebra.general.classes.ProductSet.defaultGetElementFrom(ProductSet.java:78)
        at ch.bfh.unicrypt.math.algebra.general.abstracts.AbstractSet.getElementFrom(AbstractSet.java:347)
        at ch.bfh.unicrypt.math.algebra.general.classes.ProductSet.defaultGetElementFrom(ProductSet.java:300)
        at ch.bfh.unicrypt.math.algebra.general.classes.ProductSet.defaultGetElementFrom(ProductSet.java:78)
        at ch.bfh.unicrypt.math.algebra.general.abstracts.AbstractSet.getElementFrom(AbstractSet.java:322)

**Comment by ruescasd** [comment]
Commitment causing crash:

["25316994461316114484844849220354998990012171245875102838371994628431750386500265073515348025626993102220022716868394807
487123047971952454659583248194635466828410157899820607881701208788965834073523625848343625663141395288182561232439200555119459410133826984258147267440455045720780276782273739030609146165490
820068739811365536630532848183394191726731771074231454612296711010814543152886052840761271266109464894554378518038198246998405284610674907307268522991890120950780609858148585943600502374083
21638776799067539777205013724792353716281938019575264089267766416037215402858471988057961099246300166515770976427480009"|["119785084327815390419186149288746007811302488587871537400834387793
327858962322348258362988813683344096236967576092388599069279556190884101231808965826000129154555377114612947732442545086936030263727900979047786405579412957908176027439950038677998498114298
169623338913489342272927168527806996106691521206096025190300546533063258050617530305304768812953693459690317022401377633132261999309570794262422906947936816728161636090478208911096157472131
10171410283635804370497208656086698510173803095229145399618685771074978959255695297044068959019880590214670919415367755171548218232733189040838469144116290009456006287066434"|"1251280044836
636592691756991851249813106145330340875123538147622902261584831063659228335490579553431413982065850170889736530826567549264726461281272559086768876261338196521065133266458561765470216351642
430550889331623925547708425101061078200933561372226283049300816066167865774510973381446006503806423836147769950839561147424378103971488072723786867931838426530500375618924634791742227113264
840726518020788279272967287238269180704735237908409849809061898457369985821820767972869172011144698558754403707145688512735310481485104179024100384038213618833982355899475067077911185170064
2546416156631780335279617533852001675"]]

The set with which we are deserializing (spg.getCommitmentSpace, spg is a ReEncryptionShuffleProofSystem):

ProductGroup[GStarModSafePrime[1615850303565550365035743834433497598022205133485774201606517271376232756943394544659860070576145673184435898046094900974705977957524546054754
407619322414156031543868365049804587509887519482605339802881919203378413839610932130987808091904716923808523529082292601815252144378794577053290430377619956196519276095716669483417121034248
739328228474742808801766316102903890282966551309635423015707512929643208855836297180185923092867879917557615082295220184880661664361561356284235541010486257855086346566173483927129032834896
7522998634176499319107762583194718667771801067716614802322659239302476074096777926805529798824879] x ProductGroup[GStarModSafePrime[161585030356555036503574383443349759802220513348577420160
651727137623275694339454465986007057614567318443589804609490097470597795752454605475440761932241415603154386836504980458750988751948260533980288191920337841383961093213098780809190471692380
852352908229260181525214437879457705329043037761995619651927609571666948341712103424873932822847474280880176631610290389028296655130963542301570751292964320885583629718018592309286787991755
76150822952201848806616643615613562842355410104862578550863465661734839271290328348967522998634176499319107762583194718667771801067716614802322659239302476074096777926805529798824879]^2]]

Stack trace:

UniCryptException[ELEMENT_CONVERSION_FAILURE]
        at ch.bfh.unicrypt.math.algebra.general.abstracts.AbstractSet.getElementFrom(AbstractSet.java:324)
        at ch.bfh.unicrypt.math.algebra.general.abstracts.AbstractSet.getElementFrom(AbstractSet.java:387)
        at Verifier$.verifyShuffle(Verifier.scala:158)
        at Election$.addMix(Election.scala:183)
        at ElectionTest$$anonfun$8.apply(Demo.scala:162)
        at ElectionTest$$anonfun$8.apply(Demo.scala:160)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: UniCryptException[ELEMENT_CONVERSION_FAILURE]
        at ch.bfh.unicrypt.math.algebra.general.classes.ProductSet.defaultGetElementFrom(ProductSet.java:291)
        at ch.bfh.unicrypt.math.algebra.general.classes.ProductSet.defaultGetElementFrom(ProductSet.java:78)
        at ch.bfh.unicrypt.math.algebra.general.abstracts.AbstractSet.getElementFrom(AbstractSet.java:347)
        at ch.bfh.unicrypt.math.algebra.general.classes.ProductSet.defaultGetElementFrom(ProductSet.java:300)
        at ch.bfh.unicrypt.math.algebra.general.classes.ProductSet.defaultGetElementFrom(ProductSet.java:78)
        at ch.bfh.unicrypt.math.algebra.general.abstracts.AbstractSet.getElementFrom(AbstractSet.java:322)

**Comment by ruescasd** [comment]
So far more than 4M extra votes processed with no further crashes, bug seems to have disappeared mysteriously. Possibly fixed by this change:

https://github.com/agoravoting/sandbox/commit/6c569d03d3289c3c6f18a7d22ec3397734f3f6d1

although it makes no sense why this would be the case. Leaving traces in place if it resurfaces.
